apiVersion: apps/v1
kind: Deployment
metadata:
  name: linkding
  labels:
    app: linkding
    version: v1
spec:
  replicas: 1
  selector:
    matchLabels:
      app: linkding
      version: v1
  template:
    metadata:
      labels:
        app: linkding
        version: v1
    spec:
      containers:
        - name: linkding
          image: sissbruecker/linkding:1.39.1
          ports:
            - containerPort: 9090
          volumeMounts:
            - name: linkding-data
              mountPath: /etc/linkding/data
      volumes:
        - name: linkding-data
          persistentVolumeClaim:
            claimName: linkding-data-pvc
---
apiVersion: v1
kind: Service
metadata:
  name: linkding-service
spec:
  type: NodePort
  selector:
    app: linkding
  ports:
    - port: 9090
      targetPort: 9090
      nodePort: 30007
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: linkding-data-pvc
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
