---
# Source: kubewall/templates/pvc.yaml
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: kubewall-data
  namespace: kubewall-system
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 20Mi
