apiVersion: v1
kind: Service
metadata:
  name: commafeed-clusterip
  namespace: commafeed
  labels:
    app: commafeed
spec:
  type: ClusterIP
  ports:
    - port: 8082
      targetPort: 8082
      protocol: TCP
      name: http
  selector:
    app: commafeed
---
apiVersion: v1
kind: Service
metadata:
  name: commafeed-nodeport
  namespace: commafeed
  labels:
    app: commafeed
spec:
  type: NodePort
  ports:
    - port: 8082
      targetPort: 8082
      nodePort: 31234
      protocol: TCP
  selector:
    app: commafeed
