apiVersion: external-secrets.io/v1
kind: ClusterSecretStore
metadata:
  name: infisical-papra-store
spec:
  provider:
    infisical:
      auth:
        universalAuthCredentials:
          clientId:
            key: clientId
            name: universal-auth-credentials
            namespace: external-secrets
          clientSecret:
            key: clientSecret
            name: universal-auth-credentials
            namespace: external-secrets
      caProvider:
        key: ca.crt
        name: infisical-ca
        namespace: external-secrets
        type: ConfigMap
      hostAPI: https://infisical.lokal
      secretsScope:
        environmentSlug: papra
        expandSecretReferences: true
        projectSlug: infisical-sm-tca-z
        recursive: false
        secretsPath: /
