apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: papra-external-secret
  namespace: papra
spec:
  dataFrom:
    - find:
        conversionStrategy: Default
        decodingStrategy: None
        name:
          regexp: .*
        nullBytePolicy: Ignore
  refreshInterval: 1h0m0s
  secretStoreRef:
    kind: ClusterSecretStore
    name: infisical-papra-store
  target:
    creationPolicy: Owner
    deletionPolicy: Retain
    name: papra-infisical-secret
