apiVersion: v1
kind: PersistentVolume
metadata:
  name: papra-pv
spec:
  accessModes:
    - ReadWriteOnce
  capacity:
    storage: 10Gi
  claimRef:
    apiVersion: v1
    kind: PersistentVolumeClaim
    name: papra-pvc
    namespace: papra
  nodeAffinity:
    required:
      nodeSelectorTerms:
        - matchExpressions:
            - key: kubernetes.io/hostname
              operator: In
              values:
                - node01
  persistentVolumeReclaimPolicy: Retain
  storageClassName: custom-local-path
  volumeMode: Filesystem
  local:
    path: /home/soeguet/papra
