apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: papra-pvc
  namespace: papra
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
  storageClassName: custom-local-path
  volumeMode: Filesystem
  volumeName: papra-pv
