apiVersion: v1
kind: Service
metadata:
  name: paperless-clusterip
  namespace: paperless
spec:
  selector:
    app: paperless
  ports:
    - name: paperless-ip
      protocol: TCP
      port: 80
      targetPort: 8000
