apiVersion: v1
kind: Service
metadata:
  name: paperless
  namespace: paperless
spec:
  ports:
  - port: 8000
    protocol: TCP
    targetPort: 8000
    nodePort: 30011
  selector:
    app: paperless
  type: NodePort
