kind: ConfigMap
apiVersion: v1
metadata:
  name: immich-env
  namespace: immich
  labels:
    app: immich
data:
  DB_DATABASE_NAME: "immich"
  DB_PORT: "5432"
  UPLOAD_LOCATION: "/usr/src/app/upload"
  LOG_LEVEL: "debug"
  IMMICH_MACHINE_LEARNING_URL: "http://immich-machine-learning:3003"
  MACHINE_LEARNING_HTTP_KEEPALIVE_TIMEOUT_S: "0"
  MACHINE_LEARNING_CACHE_FOLDER: "/cache"
  ML_WORKER_ENABLED: "true"
  ML_WORKER_FACE_RECOGNITION_ENABLED: "true"
  VECTOR_EXTENSION: "vector"
  REDIS_HOSTNAME: "redis-immich-server"
  REDIS_PORT: "6379"
  REDIS_DBINDEX: "0"
  REDIS_PASSWORD: ""
  DISABLE_REVERSE_GEOCODING: "false"
  REVERSE_GEOCODING_PRECISION: "2"
  PUBLIC_LOGIN_PAGE_MESSAGE: ""
  PUID: "0"
  PGID: "0"
