apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  namespace: mealie
  name: mealie-data-pvc
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: nfs-client
  resources:
    requests:
      storage: 100Mi